# Generated by Django 4.1.2 on 2023-12-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
