# Generated by Django 4.1.2 on 2023-12-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_user_description_remove_user_image_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('link', models.URLField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='stores',
            field=models.ManyToManyField(to='books.store'),
        ),
    ]
